# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20181205_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('logo', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
